Get Assigned Doctors By Patient Id
balajisandiparthi2002/HealthCare-POC pull request #17
Opened 2024-07-19 09:46 UTC by balajisandiparthi2002

I have used $lookup stage in Aggregation pipeline to get the data from two collections. Using $lookup stage, I have retrieved the list of doctors who are assigned to the specified patient.

2024-07-22 06:26 UTC, divya-sathyan commented on src/main/java/com/theelixrlabs/healthcare/constants/MessageConstants.java
>      public static final String PATIENT_LAST_NAME_NOT_NULL = "{patient.last.name.notnull}";
Why it is inside the{}

2024-07-22 07:36 UTC, ashutosh-2609 requested changes

2024-07-22 07:36 UTC, ashutosh-2609 commented on src/main/java/com/theelixrlabs/healthcare/repository/DoctorsByPatientIdRepositoryImpl.java
> +        AggregationOperation addFieldsOperation = Aggregation.addFields()
I feel this can be modified to return List of patient with assigned doctors
similar to DoctorsByPatientDto 

Also rename DoctorsByPatientDto to PatientWithAssignedDoctorsDto

2024-07-22 09:52 UTC, balajisandiparthi2002 commented on src/main/java/com/theelixrlabs/healthcare/repository/DoctorsByPatientIdRepositoryImpl.java
> +        AggregationOperation addFieldsOperation = Aggregation.addFields()
Resolved.

2024-07-22 10:28 UTC, ashutosh-2609 approved these changes

2024-07-24 06:51 UTC, divya-sathyan approved these changes

2024-07-24 07:01 UTC, vinodkadam22 approved these changes

2024-07-24 07:11 UTC, merged