Added get patient by ID feature
balajisandiparthi2002/HealthCare-POC pull request #5
Opened 2024-07-01 06:11 UTC by SambitKSahu99

Added getPatientByID method in existing service and controller class and made some changes in Patient DTO and Model class

2024-07-01 07:16 UTC, Abhijith-Sajimon requested changes
Added comments. Please review and make changes to other areas of the code as well according to them.

2024-07-01 07:16 UTC, EXR-38 commented on src/main/java/com/theelixrlabs/healthcare/constants/PatientConstants.java
>      public static final String AADHAAR_NUMBER_ALREADY_EXISTS = "Aadhaar Number already exists.";
Please move the validation messages to messages.properties file

2024-07-01 07:16 UTC, EXR-38 commented on src/main/java/com/theelixrlabs/healthcare/controller/PatientController.java
> +import org.springframework.web.bind.annotation.*;
Remove the wild card imports

2024-07-01 07:16 UTC, EXR-38 commented on src/main/java/com/theelixrlabs/healthcare/controller/PatientController.java
> +        } catch (Exception exception) {
Better to specify the exception you are trying to catch here. You can add another catch block to account for the generic exceptions.

2024-07-01 07:16 UTC, EXR-38 commented on src/main/java/com/theelixrlabs/healthcare/service/PatientService.java
> +        if (patientDTO.getPatientFirstName().isEmpty()) {
What if the patientDTO object is null?

2024-07-01 07:16 UTC, Abhijith-Sajimon commented on src/main/java/com/theelixrlabs/healthcare/service/PatientService.java
> +        if (patientRepository.findByPatientAadhaarNumber(formattedAadhaarNumber).isPresent()) {
Make the return value of findByPatientAadhaarNumber() optional to accomodate the possibility of it returning null.

2024-07-01 08:30 UTC, SambitKSahu99 commented on src/main/java/com/theelixrlabs/healthcare/service/PatientService.java
> +        if (patientDTO.getPatientFirstName().isEmpty()) {
Before passing the Patient DTO object to service layer , in controller we are validating it and then we are sending.

2024-07-01 08:31 UTC, SambitKSahu99 commented on src/main/java/com/theelixrlabs/healthcare/service/PatientService.java
> +        if (patientRepository.findByPatientAadhaarNumber(formattedAadhaarNumber).isPresent()) {
In repository layer return type of findByPatientAadhaarNumber() is optional

2024-07-02 05:02 UTC, SambitKSahu99 commented on src/main/java/com/theelixrlabs/healthcare/constants/PatientConstants.java
>      public static final String AADHAAR_NUMBER_ALREADY_EXISTS = "Aadhaar Number already exists.";
Resolved

2024-07-02 05:02 UTC, SambitKSahu99 commented on src/main/java/com/theelixrlabs/healthcare/controller/PatientController.java
> +import org.springframework.web.bind.annotation.*;
Resolved

2024-07-02 05:02 UTC, SambitKSahu99 commented on src/main/java/com/theelixrlabs/healthcare/controller/PatientController.java
> +        } catch (Exception exception) {
Resolved

2024-07-02 11:56 UTC, Abhijith-Sajimon approved these changes

2024-07-02 12:05 UTC, ashutosh-2609 approved these changes

2024-07-03 04:06 UTC, merged